# Generated by Django 5.0.4 on 2024-07-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bags',
            new_name='Bag',
        ),
    ]
